### ISSUE TITLE
ExampleData Error when running the Analysis

### ISSUE THREAD

**Issue by dfu732** [biobenkj/SPARTA_Mac#1]
Error in read.table("/Users/DavidFu/Desktop/RNAseq_Data/2015-08-05_1/DEanalysis/mapgly7a.sam",  : 
  no lines available in input

What does this mean? It won't let me execute the data properly when I try to run the sample data. Thanks!

**Comment by biobenkj** [comment]
You can open up the file in a text editor and see if there is anything inside.

It should look something like this with many more lines after it.

MT0001  20
MT0002  16
MT0003  5
MT0004  2
MT0005  34
MT0006  22
MT0007  4
MT0009  0
MT0010  2
MT0011  19
MT0012  3
MT0013  1
MT0014  4
MT0015  8
MT0016  3

I suspect that there was an error earlier in the analysis that is leading to this error. Scroll back in the terminal to see if you can find any other errors that were displayed and post them here. Thanks for the feedback!

**Comment by dfu732** [comment]
Thank you for the quick response! Sorry, I'm just a undergraduate trying to get a grasp on RNA seq before the school year starts and am thus fairly new to all of this programming and what not. When I opened the mapgly7.sam file in TextEdit, there was no data/information in it at all and was completely blank. As for an error, this is my readout after the instructions of how to edit the file in the RNAseq_Data folder.
Bioconductor version 3.0 (BiocInstaller 1.16.5), ?biocLite for helpA new version of Bioconductor is available after installing the most recent  version of R; see http://bioconductor.org/installBioC_mirror: http://bioconductor.orgUsing Bioconductor version 3.0 (BiocInstaller 1.16.5), R version 3.1.3.Installing package(s) 'edgeR'trying URL 'http://bioconductor.org/packages/3.0/bioc/bin/macosx/contrib/3.1/edgeR_3.8.6.tgz'Content type 'application/x-gzip' length 1188191 bytes (1.1 MB)opened URL==================================================downloaded 1.1 MB

The downloaded binary packages are in /var/folders/w5/h28jwnf57nq96z8m7kfxt4m80000gn/T//RtmpKE95ty/downloaded_packagesOld packages: 'boot', 'codetools', 'lattice', 'MASS', 'Matrix', 'mgcv'Loading required package: limmaError in read.table("/Users/DavidFu/Desktop/RNAseq_Data/2015-08-07/DEanalysis/mapgly7a.sam",  :   no lines available in inputExecution haltedAnalysis complete. Thank you for using SPARTA.
Thank you for your help! 

```
 On Wednesday, August 5, 2015 3:02 PM, Ben Johnson <notifications@github.com> wrote:
```

 You can open up the file in a text editor and see if there is anything inside.It should look something like this with many more lines after it.MT0001 20
MT0002 16
MT0003 5
MT0004 2
MT0005 34
MT0006 22
MT0007 4
MT0009 0
MT0010 2
MT0011 19
MT0012 3
MT0013 1
MT0014 4
MT0015 8
MT0016 3I suspect that there was an error earlier in the analysis that is leading to this error. Scroll back in the terminal to see if you can find any other errors that were displayed and post them here. Thanks for the feedback!—

**Comment by biobenkj** [comment]
That's fantastic that you are trying to wrap your head around RNA-seq as an undergrad!

So I think the error may have occurred even earlier in the analysis (probably in the HTSeq section). If you could do a couple things for me: 1) Scroll further back in the analysis and see if there were any errors either in HTSeq or Bowtie [might look like "./htseq-count not found"], 2) See if the intermediate files have any data in them (you can do this just by looking at the file size [should be greater than 0 kb]), and 3) make sure the dependencies are properly installed.

Let me know what you find.

**Comment by dfu732** [comment]
I think you're right about it being an error with HTSeq. Here's the output:
Counting gene features with HTSeq/bin/sh: ./htseq-count: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Content: bad interpreter: No such file or directory/bin/sh: ./htseq-count: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Content: bad interpreter: No such file or directory/bin/sh: ./htseq-count: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Content: bad interpreter: No such file or directory/bin/sh: ./htseq-count: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Content: bad interpreter: No such file or directory/bin/sh: ./htseq-count: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Content: bad interpreter: No such file or directory/bin/sh: ./htseq-count: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Content: bad interpreter: No such file or directory/bin/sh: ./htseq-count: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Content: bad interpreter: No such file or directory/bin/sh: ./htseq-count: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Content: bad interpreter: No such file or directory 

```
 On Friday, August 7, 2015 10:29 AM, Ben Johnson <notifications@github.com> wrote:
```

 That's fantastic that you are trying to wrap your head around RNA-seq as an undergrad!So I think the error may have occurred even earlier in the analysis (probably in the HTSeq section). If you could do a couple things for me: 1) Scroll further back in the analysis and see if there were any errors either in HTSeq or Bowtie [might look like "./htseq-count not found"], 2) See if the intermediate files have any data in them (you can do this just by looking at the file size [should be greater than 0 kb]), and 3) make sure the dependencies are properly installed.Let me know what you find.—

**Comment by biobenkj** [comment]
Hm. This appears to be a Python issue actually. So for some reason, there is a broken link and it can't find the interpreter. Here is what I suggest to do.

(Re)Install the latest version of Python 2.7 for Mac OSX which is 2.7.10 (https://www.python.org/downloads/mac-osx/)

Re-run the NumPy installation after you've completed the Python installation by running within the terminal: sudo pip install numpy

Let me know if this fixes the issue. Thanks!

**Comment by dfu732** [comment]
Looks like it worked. Thank you very much! 

```
 On Friday, August 7, 2015 12:21 PM, Ben Johnson <notifications@github.com> wrote:
```

 Hm. This appears to be a Python issue actually. So for some reason, there is a broken link and it can't find the interpreter. Here is what I suggest to do.(Re)Install the latest version of Python 2.7 for Mac OSX which is 2.7.10 (https://www.python.org/downloads/mac-osx/)Re-run the NumPy installation after you've completed the Python installation by running within the terminal: sudo pip install numpyLet me know if this fixes the issue. Thanks!—

**Comment by biobenkj** [comment]
Great! Thanks for using the workflow. Best of luck this year in school.

**Comment by dfu732** [comment]
Hello!
It's me again, David Fu. I just got a RNA seq case from my professor to toy around with and had a couple of questions. Does SPARTA have a human genome reference? If not, how would I implement that?
Thanks! 

```
 On Friday, August 7, 2015 2:57 PM, Ben Johnson <notifications@github.com> wrote:
```

 Great! Thanks for using the workflow. Best of luck this year in school.—
