### ISSUE TITLE
Human Genome as Reference?

### ISSUE THREAD

**Issue by dfu732** [biobenkj/SPARTA_Mac#2]
Hi! Do you guys use the human genome as a reference or would I need to download that and check it with my case data?

Thanks!

**Comment by dfu732** [comment]
Actually I just figured out bacterial genome is the one that's used as a reference. If I needed to use human genome and paired end samples, could I still use this program or would I have to find a new one?

**Comment by biobenkj** [comment]
Unfortunately, SPARTA is aimed at bacterial RNA-seq data sets. You can download the human genome from Ensembl but it is a large file and you may not want that on your personal computer. I would recommend working on Galaxy (https://galaxyproject.org/). It is a cloud based system that is a drag and drop setup for analyzing human RNA-seq data that may already have the human genome on it. 

In the future, SPARTA will have paired-end reads support, but for now, it is simply for single-end.

Also, I would recommend the "Tuxedo suite" designed by the Broad institute as a first pass for working through human RNA-seq data (http://www.broadinstitute.org/cancer/software/genepattern/rna-seq-analysis) on Galaxy.

Best of luck!
